### ISSUE TITLE
Unable to use vars in Schema Owner

### ISSUE THREAD

**Issue by toadies** [Titan-Systems/titan#175]
Building a template for our schemas and trying to use vars on owner.  The vars works with name to create the role.

```
schemas:
  - name: "{{ var.schema }}"
    managed_access: true
    owner: "{{ var.database }}_{{ var.schema }}_R_AR"
    comment: AUTO-PROVISION BY TITAN
```

results in following error
```
venv/lib/python3.10/site-packages/titan/identifiers.py", line 236, in parse_identifier
    raise pp.ParseException(f"Failed to parse identifier: {identifier}")
pyparsing.exceptions.ParseException: Failed to parse identifier: {{ var.database }}_{{ var.schema }}_R_AR  (at char 0), (line:1, col:1)
```

**Comment by toadies** [comment]
Same issue trying to use variables with database_roles

```
database_roles:
  - name: "{{ var.database }}_{{ var.schema }}_FULL_AR"
    database: "DV_SOURCES_DB"
    owner: USERADMIN
    comment: AUTO-PROVISION BY TITAN
```

error emssage
```
venv/lib/python3.10/site-packages/titan/blueprint.py", line 456, in _merge_pointers
    if resource_id in namespace:
TypeError: unhashable type: 'VarString'
```

CLI works when hard coding a value in `database`.

**Comment by teej** [comment]
Fixed in [v0.11.1](https://github.com/Titan-Systems/titan/releases/tag/v0.11.1)

**Comment by toadies** [comment]
Similar error still on using variable in database for database_roles

```
database_roles:
  - name: "{{ var.database }}_{{ var.schema }}_FULL_AR"
    database: "{{ var.database }}"
    owner: USERADMIN
```

error
```
venv/lib/python3.10/site-packages/titan/blueprint.py", line 456, in _merge_pointers
    if resource_id in namespace:
TypeError: unhashable type: 'VarString'
```

**Comment by teej** [comment]
I'll retest
